name: rapyd
description: Rapyd Flutter SDK for accessing the Payments API
version: 0.1.0
homepage: https://github.com/sbis04/rapyd_sdk_flutter

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.4
  convert: ^3.0.1
  crypto: ^3.0.2

dev_dependencies:
  test: ^1.21.1
